[versions]
agp = "9.0.0-rc03"
junit = "6.0.2"
kotlin = "2.2.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-kmp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.1" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
publishReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
